# Setup
title:               sqlBro
tagline:             'do you even code bro?'
description:         'stay hungry, stay foolish'
url:                 https://stitcombe.github.io
baseurl:             ''
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Stephen
  url:               https://stitcombe.github.io/about/
  email:             05_wattage.gyms@icloud.com

# Gems
plugins:
  - jekyll-paginate
  - jemoji

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
