# Setup
title:               sqlBro
tagline:             'bro, do you even code?'
description:         'these aren''t the droids you''re looking for'
url:                 https://stitcombe.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Stephen
  url:               https://stitcombe.github.io/about/
  email:             hello@email.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
